import Layout from './components/layout/Layout'
import './globals.css'
import { ThemeProvider } from './hooks/ThemeContext'
import { SidebarProvider } from './hooks/SidebarContext'
import InitialGlobalFont from '@/app/config/font'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <InitialGlobalFont/>
      <ThemeProvider>
        <SidebarProvider>
          <html lang="en">
            <body>
              <Layout>
                {children}
              </Layout>
            </body>
          </html>
        </SidebarProvider>
      </ThemeProvider>
    </>
  )
}
